export enum URLPaths {
	TMDB = "https://api.themoviedb.org/",
	ACCOUNT = "3/account/",
	AUTHENTICATION = "3/authentication/",
	CERTIFICATION = "3/certification/",
	MOVIE = "3/movie/",
	PERSON = "3/person/",
	TV = "3/tv/",
	COLLECTION = "3/collection/",
	COMPANY = "3/company/",
	CONFIGURATION = "3/configuration",
	CREDIT = "3/credit/",
	DISCOVER = "3/discover/",
	FIND = "3/find/",
	GENRE = "3/genre/",
	GUEST_SESSION = "3/guest_session/",
	KEYWORD = "3/keyword/",
	LIST = "3/list/",
	NETWORK = "3/network/",
	REVIEW = "3/review/",
	SEARCH = "3/search",
	TRENDING = "3/trending/",
	WATCH = "3/watch/"
}